### ISSUE TITLE
Getting error in deployment while using  serverless-lambda-edge-pre-existing-cloudfront plugin 

### ISSUE THREAD

**Issue by shalu1301** [serverless-operations/serverless-lambda-edge-pre-existing-cloudfront#9]
while deploying in serverless , the error says as :
Serverless plugin "serverless-lambda-edge-pre-existing-cloudfront" initialization errored: Cannot read property 'defineCustomProperties' of undefined

**Comment by jiangzhuo** [comment]
Same issue
```
    this.serverless.configSchemaHandler.defineCustomProperties({
      type: 'object',
      properties: {
        lambdaEdgePreExistingCloudFront: {
          type: 'object',
          properties: {
            validStages: {
              type: 'array',
              items: { type: 'string' },
              uniqueItems: true
            }
          }
        },
      }
    })
```

the `configSchemaHandler` is introduced in [config schema validation feature](https://github.com/serverless/serverless/pull/7335) from serverless@1.78.0

update serverless package to a newer version may solve this issue.

**Comment by nionata** [comment]
@jiangzhuo updating serverless did the trick. Thank you!

**Comment by shalu1301** [comment]
@jiangzhuo  yes it worked thanks!!
